language: node_js
branches:
  only:
  - master
script:
    - npm build
deploy:
  provider: pages
  skip-cleanup: false
  local-dir: dist
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  on:
    branch: master
