language: node_js
node_js:
    - lts/*
branches:
  only:
  - master
script:
    - npm run build
    - ls dist/*
    - pwd
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: dist
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  on:
    branch: master
